apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
{{ include "common-labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{$key}}: {{ $value | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
{{ include "common-labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.environment }}
  {{$key}}: {{ $value | quote }}
  {{- end }}