apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
{{ include "common-labels" . | indent 4 }}
spec:
  maxReplicas: {{ .Values.scalability.maxReplicas }}
  minReplicas: {{ .Values.scalability.replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: {{ .Values.scalability.autoscaleCPUPercent }}