{{ if .Values.metrics.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
    prometheus: {{ .Values.metrics.prometheus.instance }}
{{ include "common-labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "common-labels" . | indent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Name }}
  endpoints:
    - targetPort: {{ .Values.httpService.internalPort }}
      interval: 15s
{{ end }}