apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
{{ include "common-labels" . | indent 4 }}
imagePullSecrets: []
